name:                learning-bot
version:             0.1.0.0
github:              "githubuser/learning-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/learning-bot#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- bytestring
- aeson
- aeson-pretty
- text
- directory
- unordered-containers
- vector
- mtl
- hspec

default-extensions:
- OverloadedStrings
- RecordWildCards
- DuplicateRecordFields

library:
  source-dirs: src

executables:
  learning-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-bot

tests:
  learning-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-bot
